### ISSUE TITLE
Cleanup Command

### ISSUE THREAD

**Issue by JohnnyJTH** [Carberra/Carberretta#111]
Add a Moderator command for clearing all bot messages sent in the channel in the last x hours (defaults to 1 hour).

Syntax:
```
+cleanup [timeframe=1h]

Timeframe (optional): Choose how long from now the messages will be deleted. Defaults to 1 hour back. 
```

**Comment by JohnnyJTH** [comment]
I can implement it also

**Comment by MrDogeBro** [comment]
Solaris already has a clear command so I don't really know if this is necessary.....however that command is different in some ways from the proposed command so lets see what Carbs and Max think. Its definitely an interesting idea though to use a time frame instead of a message count or whatnot......

**Comment by parafoxia** [comment]
I am planning to slowly let Carberretta take over from Solaris in a number of respects. This command would fit in with those plans, but not for the time being. Probably in a month or so I'll come back to this.

**Comment by parafoxia** [comment]
In the meantime, use `>>clear 20 @Solaris` for example and it'll clear the messages from Solaris. You can also mention multiple members in that

**Comment by JohnnyJTH** [comment]
Yep that sounds good
