### ISSUE TITLE
Support channels are not sorted.

### ISSUE THREAD

**Issue by vicky5124** [Carberra/Carberretta#18]
Current behaviour: [ScreenShot](https://5124.16-b.it/ss/21:52:05_27-09-2020.png)
Expectation: The channels to be sorted by name: Alpha, Beta, Gamma, Delta, Zeta, Epsilon.

Edit: also happens on un/available.

**Comment by parafoxia** [comment]
Okay so it seems it *is* fixed - it just took a while to sort out.

**Comment by parafoxia** [comment]
So turns out it's not. Sometimes the channels do match up, sometimes they don't. Will have to do some investigation.

**Comment by nitsuga5124** [comment]
probably the channel patch ratelimits

**Comment by parafoxia** [comment]
> probably the channel patch ratelimits

I highly doubt it. That only affects names and topics, and most of the time, channels wait way longer than 10 minutes to be moved.

The problem is either related to the number of channels the support system has to deal with, or more likely, the fact that the indexes are getting confused because more than one channel is missing from the set.

Neither of these should be an issue though, and we physically can not recreate the problem in testing, so a diagnosis is proving difficult.
